global:
  scrape_interval: 4s  # Fixed indentation

scrape_configs:
  - job_name: 'nextjs_app'
    metrics_path: '/api/metrics' 
    static_configs:
      - targets: ['192.168.1.37:3000']  # Ensure this is correct
