// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Providers } from "./provider";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={inter.className}>


//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* SignedIn: Content shown when user is authenticated */}
          <SignedIn>
            <UserButton afterSignOutUrl="/" />
            {children}
          </SignedIn>

          {/* SignedOut: Content shown when user is not authenticated */}
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
