// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={inter.className}>
//           {/* SignedIn: Content shown when user is authenticated */}
//           <SignedIn>
//             <UserButton afterSignOutUrl="/" />
//             {children}
//           </SignedIn>

//           {/* SignedOut: Content shown when user is not authenticated */}
//           <SignedOut>
//             <SignInButton />
//           </SignedOut>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"; // Keep only ClerkProvider here

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* Render children inside the ClientAuthWrapper */}
          <ClientAuthWrapper>{children}</ClientAuthWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
